// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Helpers;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201107094700_GoodsReceivingNote")]
    partial class GoodsReceivingNote
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "6d176cd3-bb32-446e-8805-d8d846b1e224",
                            ConcurrencyStamp = "b1e783d2-29a2-4ad1-af8e-e9871e78ffbf",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "9763a45d-acad-4d5a-a6c0-6c395007765e",
                            ConcurrencyStamp = "64d37a32-d1eb-4e4b-b8f2-defd8a1a4a65",
                            Name = "Sale",
                            NormalizedName = "sale"
                        },
                        new
                        {
                            Id = "0d5b49f3-9c6e-400d-905d-1ce4c32fe89f",
                            ConcurrencyStamp = "5b0531cc-df23-4e30-9490-4d20faf18f7e",
                            Name = "SuperAdmin",
                            NormalizedName = "superadmin"
                        },
                        new
                        {
                            Id = "fd8e5cfa-30ae-473b-9ca3-c43d28c29f9f",
                            ConcurrencyStamp = "065d9b34-5b71-4508-8536-a3d9000faef3",
                            Name = "WarehouseKeeperManager",
                            NormalizedName = "warehousekeepermanager"
                        },
                        new
                        {
                            Id = "80c68b9a-9567-4acf-a1a1-55cd93489a5e",
                            ConcurrencyStamp = "4d128e77-4fa3-4c0f-a8a2-64cb27755987",
                            Name = "WarehouseKeeper",
                            NormalizedName = "warehousekeeper"
                        },
                        new
                        {
                            Id = "875f2812-b28f-4135-bf58-f072fe3de158",
                            ConcurrencyStamp = "7e8fc4a0-8b21-43ec-91c6-39aba0c3cac3",
                            Name = "Customer",
                            NormalizedName = "customer"
                        },
                        new
                        {
                            Id = "2027c67f-9417-47a7-89c4-da9bd5072fd4",
                            ConcurrencyStamp = "e1228026-fae5-42b4-992a-d8a55f951d4c",
                            Name = "Boss",
                            NormalizedName = "boss"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "019c57e9-704a-4719-b836-ec61e2b31f0f",
                            RoleId = "6d176cd3-bb32-446e-8805-d8d846b1e224"
                        },
                        new
                        {
                            UserId = "8a5d8929-1f42-4d11-a9f6-e4f42580e51e",
                            RoleId = "0d5b49f3-9c6e-400d-905d-1ce4c32fe89f"
                        },
                        new
                        {
                            UserId = "03b3d9a5-e863-4e98-a953-5770975a9bad",
                            RoleId = "2027c67f-9417-47a7-89c4-da9bd5072fd4"
                        },
                        new
                        {
                            UserId = "07aac85e-183b-4674-8423-41ae14ea7450",
                            RoleId = "2027c67f-9417-47a7-89c4-da9bd5072fd4"
                        },
                        new
                        {
                            UserId = "c197acbd-9ab8-45d6-bf90-58de9792cddc",
                            RoleId = "875f2812-b28f-4135-bf58-f072fe3de158"
                        },
                        new
                        {
                            UserId = "82b0beeb-18c0-4bb8-b2d9-a4c62f02f449",
                            RoleId = "875f2812-b28f-4135-bf58-f072fe3de158"
                        },
                        new
                        {
                            UserId = "5c32abf2-3dd2-4b16-a50f-bdc06d8edcaa",
                            RoleId = "875f2812-b28f-4135-bf58-f072fe3de158"
                        },
                        new
                        {
                            UserId = "e11a5c32-6e8d-4c61-9f5a-8ef49dca5a7c",
                            RoleId = "875f2812-b28f-4135-bf58-f072fe3de158"
                        },
                        new
                        {
                            UserId = "f7cb4b66-1c25-49ea-983b-c267e5ecc916",
                            RoleId = "875f2812-b28f-4135-bf58-f072fe3de158"
                        },
                        new
                        {
                            UserId = "61538861-71d6-44d1-81b7-9ec0e0262c54",
                            RoleId = "fd8e5cfa-30ae-473b-9ca3-c43d28c29f9f"
                        },
                        new
                        {
                            UserId = "b662d244-731d-4a9d-b0b5-56d0d361ff0f",
                            RoleId = "fd8e5cfa-30ae-473b-9ca3-c43d28c29f9f"
                        },
                        new
                        {
                            UserId = "9dacd3c4-0de2-4aef-9f6f-70cfe2804c33",
                            RoleId = "80c68b9a-9567-4acf-a1a1-55cd93489a5e"
                        },
                        new
                        {
                            UserId = "275ccd8e-f8c5-4b18-b7ef-96138b62670e",
                            RoleId = "80c68b9a-9567-4acf-a1a1-55cd93489a5e"
                        },
                        new
                        {
                            UserId = "fa91cfed-d3e5-495a-998d-8939a753f2a6",
                            RoleId = "80c68b9a-9567-4acf-a1a1-55cd93489a5e"
                        },
                        new
                        {
                            UserId = "30dab8fa-2de3-43e9-9196-f4174d3ef369",
                            RoleId = "9763a45d-acad-4d5a-a6c0-6c395007765e"
                        },
                        new
                        {
                            UserId = "9e26febb-7d23-4fb7-9a3a-fc084a26a79a",
                            RoleId = "9763a45d-acad-4d5a-a6c0-6c395007765e"
                        },
                        new
                        {
                            UserId = "f352c3a6-8828-412d-b577-f03670d99119",
                            RoleId = "9763a45d-acad-4d5a-a6c0-6c395007765e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("api.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8a5d8929-1f42-4d11-a9f6-e4f42580e51e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad0bd460-fe38-47cd-ba36-89c9a2cbf325",
                            Email = "lilsuperadmin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super Admin",
                            LastName = "Lil",
                            LockoutEnabled = false,
                            NormalizedEmail = "LILSUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "LILSUPERADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKQX5UwDAxB6VR5wzoXPqZJiNti9DjUSfd3SlMrtWriLE7UKzQbO4clDebwy7BIWdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "lilsuperadmin@gmail.com"
                        },
                        new
                        {
                            Id = "019c57e9-704a-4719-b836-ec61e2b31f0f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75054df3-4719-4b8f-a829-21e5e86566c8",
                            Email = "yungadmin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Yung",
                            LockoutEnabled = false,
                            NormalizedEmail = "YUNGADMIN@GMAIL.COM",
                            NormalizedUserName = "YUNGADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB8VDNLUJPDNooZt+BmoLFB/Aurhak83zk1xjNb7Yrp7dYbqqRG5LlSNZufB92Mr5w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "yungadmin@gmail.com"
                        },
                        new
                        {
                            Id = "03b3d9a5-e863-4e98-a953-5770975a9bad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13e57c27-f665-48b2-a34a-ec98a853fd4b",
                            Email = "trankieuloan@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Loan",
                            LastName = "Trần Kiều",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRANKIEULOAN@GMAIL.COM",
                            NormalizedUserName = "TRANKIEULOAN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIqx5PbgGbwSYUMBspwhPekhYElK6TFIpyVMdgEXRAfdIUE6v+21LPlDvu/pFgMp5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "trankieuloan@gmail.com"
                        },
                        new
                        {
                            Id = "07aac85e-183b-4674-8423-41ae14ea7450",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9e9b119-980c-410d-aa53-389ce4b7cd5a",
                            Email = "phamvinhson@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sơn",
                            LastName = "Phạm Vĩnh",
                            LockoutEnabled = false,
                            NormalizedEmail = "PHAMVINHSON@GMAIL.COM",
                            NormalizedUserName = "PHAMVINHSON@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPLHwasOyqWL62MdFV/yi1ALu6ch6dO41HvxQ4UQ46qADp9Myfzzi9cxWfQ5LuZrFw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "phamvinhson@gmail.com"
                        },
                        new
                        {
                            Id = "c197acbd-9ab8-45d6-bf90-58de9792cddc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d3cdb0f8-6d6e-4605-8c2c-48bdaa3bcf45",
                            Email = "nguyentrunghieu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hiếu",
                            LastName = "Nguyễn Trung",
                            LockoutEnabled = false,
                            NormalizedEmail = "NGUYENTRUNGHIEU@GMAIL.COM",
                            NormalizedUserName = "NGUYENTRUNGHIEU@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKZiOI90Vpd+iZkNBRMkUcHPkTXKe+qtf4+PgdR7DxRp+S2FVnFFNZDXLdF+8U1m8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nguyentrunghieu@gmail.com"
                        },
                        new
                        {
                            Id = "82b0beeb-18c0-4bb8-b2d9-a4c62f02f449",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "266519b6-7982-4d9d-a657-87b9aaffe6a2",
                            Email = "nguyennhuloc@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Lộc",
                            LastName = "Nguyễn Như",
                            LockoutEnabled = false,
                            NormalizedEmail = "NGUYENNHULOC@GMAIL.COM",
                            NormalizedUserName = "NGUYENNHULOC@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFptRCCD/+oppbp0HJQ9i0R555cT9xjNbpuSayMDEKnpVCKxLQe5DUqB3wP/4hrZ7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nguyennhuloc@gmail.com"
                        },
                        new
                        {
                            Id = "5c32abf2-3dd2-4b16-a50f-bdc06d8edcaa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89aaf398-feea-4f8d-ac17-af8cfbf2e8f0",
                            Email = "caothivananh@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Anh",
                            LastName = "Cao Thị Vân",
                            LockoutEnabled = false,
                            NormalizedEmail = "CAOTHIVANANH@GMAIL.COM",
                            NormalizedUserName = "CAOTHIVANANH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAwGc041NyQibDstbDMwUHHSCvw5iRYXbnTz6524G6535mnNZrOOCmSn4Gmq3CnO0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "caothivananh@gmail.com"
                        },
                        new
                        {
                            Id = "e11a5c32-6e8d-4c61-9f5a-8ef49dca5a7c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "049b89ed-018a-4c9b-ae43-9fb2d16f7fec",
                            Email = "tranthaonguyen@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nguyên",
                            LastName = "Trần Thảo",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRANTHAONGUYEN@GMAIL.COM",
                            NormalizedUserName = "TRANTHAONGUYEN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENQ+KwXfPJJHW0k7xFbbWg0HCUwaGiTt3oE1btONorWNZOQBWQpsajdBEnqNZoO3kA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "tranthaonguyen@gmail.com"
                        },
                        new
                        {
                            Id = "f7cb4b66-1c25-49ea-983b-c267e5ecc916",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b274671-e053-47f7-8f7b-362f86f9a7d1",
                            Email = "truongthitramanh@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Anh",
                            LastName = "Trương Thị Trâm",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRUONGTHITRAMANH@GMAIL.COM",
                            NormalizedUserName = "TRUONGTHITRAMANH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMNQ24PPYH6cDJxWzfmTB8uQYUV61zN61lXJ2KMSSCvk48boB+VtQTIyrCdPGhRAuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "truongthitramanh@gmail.com"
                        },
                        new
                        {
                            Id = "61538861-71d6-44d1-81b7-9ec0e0262c54",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fc42bc03-110b-46ab-8b95-47ecbcb5a419",
                            Email = "caobaquat@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Quát",
                            LastName = "Cao Bá",
                            LockoutEnabled = false,
                            NormalizedEmail = "CAOBAQUAT@GMAIL.COM",
                            NormalizedUserName = "CAOBAQUAT@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHy1fZAKT/OPZuOiArv4jj+r/RqUDVLrUK4g6VZ8J2JBTxfFVNIx30fl7ZWl1AiL+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "caobaquat@gmail.com"
                        },
                        new
                        {
                            Id = "b662d244-731d-4a9d-b0b5-56d0d361ff0f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22995175-3364-4cf6-86fa-31bd17643dd5",
                            Email = "huynhtranthanh@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Thành",
                            LastName = "Huỳnh Trấn",
                            LockoutEnabled = false,
                            NormalizedEmail = "HUYNHTRANTHANH@GMAIL.COM",
                            NormalizedUserName = "HUYNHTRANTHANH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBZC5FDMzCqYnt5VAaBN/aiqVVIirrC9d19Rt8M6sCx0gVR9bM4S1GYSPaSF7LusuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "huynhtranthanh@gmail.com"
                        },
                        new
                        {
                            Id = "9dacd3c4-0de2-4aef-9f6f-70cfe2804c33",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af2ae480-2ad1-4d5a-8f70-816716435b38",
                            Email = "nguyenthanhlong@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Long",
                            LastName = "Nguyễn Thành",
                            LockoutEnabled = false,
                            NormalizedEmail = "NGUYENTHANHLONG@GMAIL.COM",
                            NormalizedUserName = "NGUYENTHANHLONG@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDQHV4XUG5TZkDKFKJDQs1rrciOhUDWgby5Xo4b68T1eLLo+JpNRjGfGuGKGw10O8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nguyenthanhlong@gmail.com"
                        },
                        new
                        {
                            Id = "275ccd8e-f8c5-4b18-b7ef-96138b62670e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab4d4f15-c583-40ec-8ec6-fe7dc0612136",
                            Email = "hoxuanhuong@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hương",
                            LastName = "Hồ Xuân",
                            LockoutEnabled = false,
                            NormalizedEmail = "HOXUANHUONG@GMAIL.COM",
                            NormalizedUserName = "HOXUANHUONG@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECDLpApFU4iv1rNrtWcHcYE4GXb0518djKuJu+PucS12tjaUcM5zRPH5Go8AH0HSzg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "hoxuanhuong@gmail.com"
                        },
                        new
                        {
                            Id = "fa91cfed-d3e5-495a-998d-8939a753f2a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0de06739-0cb1-49fd-98ca-f4e1d90a785a",
                            Email = "nguyenhue@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Huệ",
                            LastName = "Nguyễn",
                            LockoutEnabled = false,
                            NormalizedEmail = "NGUYENHUE@GMAIL.COM",
                            NormalizedUserName = "NGUYENHUE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAPusCRxCdA3+McuwiUJI/NXp9bexaFRuEEPVYHlu0sTWb/P/w0R/0hKO5JN0ZK4bA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nguyenhue@gmail.com"
                        },
                        new
                        {
                            Id = "30dab8fa-2de3-43e9-9196-f4174d3ef369",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a623a907-6676-447d-88b8-27b6128c47a6",
                            Email = "phungthanhdo@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Độ",
                            LastName = "Phùng Thanh",
                            LockoutEnabled = false,
                            NormalizedEmail = "PHUNGTHANHDO@GMAIL.COM",
                            NormalizedUserName = "PHUNGTHANHDO@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELk9dr++Vs3S7c2Ocbe0Oar+0Dwkd8IutL7EIIHXWxyb9HV0a+LHZUce1Fy0kMXaVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "phungthanhdo@gmail.com"
                        },
                        new
                        {
                            Id = "9e26febb-7d23-4fb7-9a3a-fc084a26a79a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f06609ea-a768-40ea-b0b5-e7360bb41882",
                            Email = "phantantrung@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Trung",
                            LastName = "Phan Tấn",
                            LockoutEnabled = false,
                            NormalizedEmail = "PHANTANTRUNG@GMAIL.COM",
                            NormalizedUserName = "PHANTANTRUNG@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEb7Bak5c7KJSi1xNY7A+dhRpj7x7USLLW/ef9vyIB3xRGmocfhTq+vvntY/va1yEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "phantantrung@gmail.com"
                        },
                        new
                        {
                            Id = "f352c3a6-8828-412d-b577-f03670d99119",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab7e63fa-ffd6-4f01-9bee-fcf491e52cd2",
                            Email = "truongtuantu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Tú",
                            LastName = "Trương Tuấn",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRUONGTUANTU@GMAIL.COM",
                            NormalizedUserName = "TRUONGTUANTU@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGcSdLuN36qZEdDLpEbHQMbvZBv991xAfZIlXEPmtsiqff+SefjbAfwO+oVLVEJyOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "truongtuantu@gmail.com"
                        });
                });

            modelBuilder.Entity("api.Entities.GoodsReceivingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodsReceivingNoteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceivingNoteId");

                    b.HasIndex("ProductId");

                    b.ToTable("GoodsReceivingDetails");
                });

            modelBuilder.Entity("api.Entities.GoodsReceivingNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GoodsReceivingNotes");
                });

            modelBuilder.Entity("api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSaledDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MaxQuantity")
                        .HasColumnType("float");

                    b.Property<double?>("MinQuantity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("QuantityForSale")
                        .HasColumnType("float");

                    b.Property<double>("QuantityOrdered")
                        .HasColumnType("float");

                    b.Property<double>("QuantityReturned")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Bơ Đăk Lăk",
                            Price = 90000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 262.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00048",
                            Status = 1
                        },
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Bòn Bon Thái",
                            Price = 25000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 896.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00001",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Bưởi Đoan Hùng",
                            Price = 60000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 259.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00002",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Cam Xã Đoài (Vinh, Nghệ An)",
                            Price = 85000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 251.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00003",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Cam xoàn Lai Vung",
                            Price = 65000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 979.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00004",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chanh dây",
                            Price = 47000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 6.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00005",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chôm chôm nhãn",
                            Price = 64000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 311.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00006",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chôm chôm Thái",
                            Price = 19000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 900.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00007",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chuối cau lửa",
                            Price = 41000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 21.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00008",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chuối già hương",
                            Price = 15000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 298.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00009",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chuối sứ",
                            Price = 15000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 592.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00010",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dâu tây Đà Lạt",
                            Price = 96000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 171.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00011",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Đu đủ vàng",
                            Price = 27000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 543.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00012",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dưa đỏ không hạt",
                            Price = 15000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 253.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00013",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dưa hấu hắc mỹ nhân",
                            Price = 35000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 324.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00014",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dưa lê trắng",
                            Price = 63000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 743.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00015",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dưa lưới giống Nhật",
                            Price = 345000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 811.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00016",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dưa lưới ruột đỏ",
                            Price = 57000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 105.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00017",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dưa lưới vàng",
                            Price = 81000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 495.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00018",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dứa Việt Nam",
                            Price = 57000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 322.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00019",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Dừa xiêm Bến Tre",
                            Price = 20000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 759.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00020",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Hồng chín Đà Lạt",
                            Price = 86000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 42.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00021",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Hồng giòn Đà Lạt",
                            Price = 34000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 728.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00022",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Hồng xiêm Tiền Giang",
                            Price = 42000.0,
                            ProductCategoryId = 1,
                            PurchasePrice = 20000.0,
                            Quantity = 420.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCVN-00023",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Cherry New Zealand Gift Box 2kg",
                            Price = 1600000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 369.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00024",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Kiwi ruột đỏ NewZealand",
                            Price = 66000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 969.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00025",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Kiwi Vàng New Zealand",
                            Price = 235000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 818.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00026",
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Kiwi Xanh New Zealand",
                            Price = 135000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 655.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00027",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo Breeze NewZealand",
                            Price = 83000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 852.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00028",
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo Envy New Zealand",
                            Price = 235000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 509.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00029",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo Jazz New Zealand",
                            Price = 110000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 904.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00030",
                            Status = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo Kiku (Size lớn) - Táo Newzealand",
                            Price = 119000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 29.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00031",
                            Status = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo Rockit Newzealand",
                            Price = 155000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 306.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00032",
                            Status = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo Royal Gala Newzealand",
                            Price = 99000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 976.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00033",
                            Status = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Táo xanh Newzealand",
                            Price = 110000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 726.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00034",
                            Status = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Chanh vàng Sunkist Mỹ",
                            Price = 51250.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 998.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00035",
                            Status = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Cherry đỏ Canada",
                            Price = 519000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 675.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00036",
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Cherry Đỏ Mỹ",
                            Price = 490000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 389.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00037",
                            Status = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Hồng giòn Mỹ",
                            Price = 409000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 813.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00038",
                            Status = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Lựu Mỹ",
                            Price = 399000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 885.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00039",
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận đen Mỹ",
                            Price = 410000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 672.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00040",
                            Status = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận đỏ Red Plum Mỹ",
                            Price = 420000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 485.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00041",
                            Status = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận khủng long (tím) Mỹ",
                            Price = 46000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 802.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00042",
                            Status = 1
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận khủng long (xanh) Mỹ",
                            Price = 420000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 764.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00043",
                            Status = 1
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận khủng long đen Mỹ",
                            Price = 109000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 439.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00044",
                            Status = 1
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận khủng long đỏ Mỹ",
                            Price = 94000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 21.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00045",
                            Status = 1
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultUnit = "Kg",
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxQuantity = 1000.0,
                            MinQuantity = 0.0,
                            Name = "Mận khủng long Farmily Tree Mỹ",
                            Price = 32000.0,
                            ProductCategoryId = 2,
                            PurchasePrice = 20000.0,
                            Quantity = 819.0,
                            QuantityForSale = 0.0,
                            QuantityOrdered = 0.0,
                            QuantityReturned = 0.0,
                            SKU = "SP-TCNK-00046",
                            Status = 1
                        });
                });

            modelBuilder.Entity("api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Trái cây Việt Nam"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Trái cây nhập khẩu"
                        });
                });

            modelBuilder.Entity("api.Entities.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("RatioFromDefault")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("api.Entities.PurchaseProposalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseProposalFormId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("QuantityPurchased")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseProposalFormId");

                    b.ToTable("PurchaseProposalDetails");
                });

            modelBuilder.Entity("api.Entities.PurchaseProposalForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OnTimeOrNotStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PurchaseProposalForms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.GoodsReceivingDetail", b =>
                {
                    b.HasOne("api.Entities.GoodsReceivingNote", "GoodsReceivingNote")
                        .WithMany("GoodsReceivingDetails")
                        .HasForeignKey("GoodsReceivingNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.Product", "Product")
                        .WithMany("GoodsReceivingDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.Product", b =>
                {
                    b.HasOne("api.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.ProductUnit", b =>
                {
                    b.HasOne("api.Entities.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.PurchaseProposalDetail", b =>
                {
                    b.HasOne("api.Entities.Product", "Product")
                        .WithMany("PurchaseProposalDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Entities.PurchaseProposalForm", "PurchaseProposalForm")
                        .WithMany("PurchaseProposalDetails")
                        .HasForeignKey("PurchaseProposalFormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.PurchaseProposalForm", b =>
                {
                    b.HasOne("api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
